/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Tag;

public class AppTest {
		@Tag("uuu")
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
				assertNotNull("app should be greeting right now");
    }
		@Tag("aaa")
		@Test public void appMightHaveGreeting() {
    		App classUnderTest = new App();
				assertEquals(43, 13+30);
		}
}
